# Generated by Django 5.1.1 on 2024-09-19 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('numero_telefono', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Inactivo', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='PlanesPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('dias_restantes', models.IntegerField()),
                ('cedula_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.clientes')),
                ('id_plan_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.planespago')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='id_plan_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.planespago'),
        ),
    ]
